name: Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  release-versions:
    name: Release version freshness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - run: make check-doc-versions
        env:
          GITHUB_TOKEN: ${{ github.token }}

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: true
      - run: make check
